Repository GDSC-RCCIIT/gdg-website, pull requests merged in 2024-10, with the labels that each got.

#52 Routing Implementation | Issue #42
  src/app/(pages)/About/page.jsx
  src/app/(pages)/Events/Events.css
  src/app/(pages)/Events/page.jsx
  src/app/(pages)/Resource/page.jsx
  src/app/(pages)/SignIn/page.jsx
  src/app/(pages)/SignUp/page.jsx
  src/app/(pages)/Subscribe/page.jsx
  src/app/(pages)/Teams&Gallery/page.jsx
  src/app/layout.js
  src/app/page.js
  src/components/Global/Header.jsx
Labels: gssoc-ext, level3

#50 Created Homepage for mobile and laptop screen
  package-lock.json
  src/app/images/ai_img.jpg
  src/app/images/teamMember.jpg
  src/app/page.js
  src/components/ui/homepage.jsx
Labels: gssoc-ext, level3

#91 Sign in sign up implementation | Form Styling Enhancements | Validation Addition | Issue #53
  src/app/(pages)/SignIn/page.jsx
  src/app/(pages)/SignUp/page.jsx
Labels: gssoc-ext, level2

#98 Framer motion added to Projects page
  src/app/(pages)/Projects/page.jsx
Labels: gssoc-ext, level3

#99 Framer animation on Resources Page
  src/app/(pages)/Resources/page.jsx
Labels: gssoc-ext, level3

#104 animation added to subscribe page
  src/app/(pages)/Resources/page.jsx
  src/app/(pages)/Subscribe/page.jsx
Labels: gssoc-ext, level3

#105 animations to teams page
  src/app/(pages)/About/page.jsx
  src/app/(pages)/TeamsGallery/page.jsx
Labels: gssoc-ext, level3

#113 Fix UI Consistancy | Issue #112
  src/app/(pages)/Projects/Card.jsx
Labels: gssoc-ext, level2

#119 Added greetings on issues and pr
  .github/workflows/greetings.yml
Labels: gssoc-ext, level2, hacktoberfest

#127 Multiple UI/UX Enhancements and Fixes
  src/app/(pages)/Events/Events.css
  src/components/Global/Footer.jsx
  src/components/Global/Header.jsx
  src/components/ui/progress-bar.jsx
Labels: gssoc-ext, level3

#128 Add hackathon page to the application
  public/hack1.jpg
  src/app/(pages)/Hackathon/Card.jsx
  src/app/(pages)/Hackathon/page.jsx
  src/components/Global/Header.jsx
  src/lib/Hackathon.js
Labels: gssoc-ext, level3

#129 Add careers page to the application
  public/sopt4.jpg
  public/spot1.jpg
  public/spot2.jpg
  public/spot3.jpg
  src/app/(pages)/careers/page.jsx
  src/components/Global/Header.jsx
Labels: gssoc-ext, level2

#130 Add searach bar to the project page
  src/app/(pages)/Projects/page.jsx
Labels: gssoc-ext, level2

#139 Landing Page animation
  src/components/Global/Hero.jsx
  src/components/ui/homepage.jsx
Labels: gssoc-ext, level3

#142 Privacy Policy Page
  src/app/(pages)/PrivacyPolicy/page.jsx
  src/components/Global/Footer.jsx
Labels: gssoc-ext, level3

#145 Rules and Regulations Page
  src/app/(pages)/RulesAndRegulations/page.jsx
  src/components/Global/Footer.jsx
Labels: gssoc-ext, level3

#154 added multilanguage support for global accessibility closes #115
  src/app/layout.js
  src/components/GTranslateLoader.js
Labels: gssoc-ext, level3

#159 Add localdev page to the website
  public/dev1.jpeg
  public/dev2.jpeg
  public/dev3.jpeg
  public/dev4.jpeg
  public/dev5.jpeg
  public/dev6.jpeg
  public/dev7.jpeg
  src/app/(pages)/localdev/page.jsx
  src/components/Global/Header.jsx
Labels: gssoc-ext, level3

#203 Add stories page to the Application for better DEV'S
  public/story1.jpeg
  public/story2.png
  public/story3.png
  public/story4.jpeg
  public/story5.png
  public/story6.png
  public/story7.png
  src/app/(pages)/stories/page.jsx
Labels: gssoc-ext, level3

#204 Implement Comprehensive Organizer Page for Enhanced Event Management Features
  src/app/(pages)/orginizer/page.jsx
Labels: gssoc-ext, level3

#210 Add Women Techmakers Page to Highlight Program and Resources for Women in Tech
  src/app/(pages)/womentechmakers/page.jsx
Labels: gssoc-ext, level3

#230 #222 Addition of DSA Learning Track and Roadmap
  .env.sample
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/[id]/page.jsx
  src/lib/dsa-content.js
  src/lib/dsa-track-content.js
Labels: gssoc-ext, level3

#239 mapped hackathon details
  data.json
  src/app/(pages)/Hackathon/[id]/page.jsx
  src/app/(pages)/Hackathon/page.jsx
Labels: gssoc-ext, level3

#251 Add Help Page for User Assistance and Support Resources
  src/app/(pages)/helpCenter/page.jsx
  src/app/(pages)/participation-terms/page.jsx
Labels: gssoc-ext, level3

#255 Add Developer Portal for Productive Development Resources and Documentation
  public/devprod1.jpeg
  public/devprod2.png
  public/devprod3.jpeg
  public/devprod4.png
  public/devprod5.jpeg
  public/devprod6.jpeg
  src/app/(pages)/devprod/page.jsx
Labels: gssoc-ext, level3

#256 Add Developer Student Club Page to Engage and Support Student Developers
  src/app/(pages)/devStudent/page.jsx
Labels: gssoc-ext, level3

#258 GDSC Chapters Endpoints Implemented | Fetch API Added for Chapters Fetch | Issue #212
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/GeminiAI/page.jsx
  src/app/(pages)/api/chapters/data.js
  src/app/(pages)/api/chapters/route.js
  src/app/(pages)/api/generate-content/generate-content.js
  src/app/(pages)/api/subscribe/subscribe.js
Labels: gssoc-ext, level3

#263 Add Git Contributors Page to Recognize Project Collaborators
  src/app/(pages)/gitContributors/page.jsx
Labels: gssoc-ext, level3

#289 hackathon form page
  package-lock.json
  package.json
  src/app/(pages)/AddHackathon/page.jsx
  src/components/Global/AddHackathonForm.jsx
Labels: gssoc-ext, level3

#277 Add Roadmap Page to Outline Future Development Plans and Milestones
  src/app/(pages)/certifications/page.jsx
  src/app/(pages)/explore/page.jsx
Labels: gssoc-ext, level3

#301 Fixed: workflow bug
  .github/workflows/auto_lable_issue.yml
Labels: gssoc-ext, level2

#278 Google's Free Certifications Page Added | To Upsikill By Google's Free Certifications & Courses | UI for Issue #188 | Issue #189
  PROJECT_STRUCTURE.md
  public/certi 1.svg
  public/certi 2.svg
  public/certi 3.svg
  public/certi 4.png
  public/certi 5.png
  repo_structure.txt
  src/app/(pages)/Certifications/page.jsx
  src/app/(pages)/certifications/page.jsx
Labels: gssoc-ext, level3

#240 made endpoints
  data.json
  src/app/(pages)/Events/page.jsx
  src/app/(pages)/Projects/Card.jsx
  src/app/(pages)/Projects/page.jsx
Labels: gssoc-ext, level3

#303 Ui: fix the home page responsiveness #299
  src/components/Global/Footer.jsx
  src/components/Global/Hero.jsx
  src/components/ui/homepage.jsx
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#306 add project page
  package-lock.json
  package.json
  src/app/(pages)/AddProjects/page.jsx
  src/components/Global/AddProjectsForm.jsx
  src/components/ui/button.jsx
  src/components/ui/form.jsx
  src/components/ui/label.jsx
Labels: gssoc-ext, level3

#308 Tech Toolkits Page
  src/app/(pages)/TechToolkits/page.jsx
  src/app/(pages)/TechToolkits/techStacks.js
Labels: gssoc-ext, level3

#288 Fixed overlapping content between header and landing page
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/components/Global/Header.jsx
Labels: gssoc-ext, level2

#284 Update README.md
  README.md
Labels: gssoc-ext, level1

#236 added contact us page
  package-lock.json
  package.json
  src/app/(pages)/Contact/Contactus.svg
  src/app/(pages)/Contact/page.jsx
  src/components/Global/Header.jsx
Labels: gssoc-ext, level3

#249 Projects details Page
  src/app/(pages)/Projects/Card.jsx
  src/app/(pages)/Projects/[id]/page.jsx
  src/app/(pages)/Projects/page.jsx
Labels: gssoc-ext, level3

#314 Adding Enhancement Request, Documentation Update template
  .github/ISSUE_TEMPLATE/documentation-update.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: gssoc-ext, level2

#316 Add Question and guideline section
  .github/ISSUE_TEMPLATE/config.yml
Labels: gssoc-ext, level1

#319 Add the PULL REQUEST TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: level1, hacktoberfest, hacktoberfest-accepted

#276 Revamp Landing Page for Enhanced User Experience and Visual Appeal || add parallax effect
  src/app/page.js
  src/components/Global/Hero.jsx
  src/components/ui/homepage.jsx
Labels: gssoc-ext, level3

#326 Add Community DevFest Page to Showcase Developer Festival Events and Resources
  src/app/(pages)/devfest/page.jsx
Labels: gssoc-ext, level3

#328 Add Tech Equity Page to Promote Inclusive Access and Equity in Technology
  public/techeq1.webp
  public/techeq2.webp
  src/app/(pages)/techequity/page.jsx
Labels: gssoc-ext, level3

#332 Add Products Navbar with Growth and Monetization Sections for Improved Navigation
  public/gro1.png
  public/gro2.png
  public/gro3.svg
  public/gro4.svg
  src/app/(pages)/devprod/page.jsx
  src/app/(pages)/growth/page.jsx
  src/components/Global/ProductsNavbar.jsx
Labels: gssoc-ext, level3

#333 Add Services and Integrations Page to Showcase Platform Capabilities
  public/ser1.png
  public/ser2.png
  public/ser3.svg
  public/ser4.svg
  src/app/(pages)/services/page.jsx
  src/components/Global/ProductsNavbar.jsx
  src/components/ui/homepage.jsx
Labels: gssoc-ext, level3
