Repository GDSC-RCCIIT/gdg-website, pull requests merged in 2024-11, with the labels that each got.

#320 bug: The navbar is not closing after clicking #305
  src/components/Global/Navbar.jsx
Labels: gssoc-ext, level2

#322 Updated readme.md by adding stargazers & forkers profiles
  README.md
Labels: good first issue, gssoc-ext, level1

#324 Added badges to the page extra info and changed the button color according to age
  data.json
  src/app/(pages)/Hackathon/Card.jsx
  src/app/(pages)/Hackathon/page.jsx
Labels: gssoc-ext, level2

#335 CREATE BUG REPORT TEMPLATE
  .github/ISSUE_TEMPLATE/bug.yml
Labels: gssoc-ext, level2

#348 Added Framer Motion Animations on 9 Pages | Issue #261
  src/app/(pages)/FAQsForum/page.jsx
  src/app/(pages)/GeminiAI/page.jsx
  src/app/(pages)/Stories-Achievements/page.jsx
  src/app/(pages)/TechToolkits/page.jsx
  src/app/(pages)/expertdev/page.jsx
  src/app/(pages)/localdev/page.jsx
  src/app/(pages)/orginizer/page.jsx
  src/app/(pages)/stories/page.jsx
  src/app/(pages)/womentechmakers/page.jsx
Labels: gssoc-ext, level3

#349 Added Support for Spotlights from JSON Server in Careers Page along with the Add Opportunity Page | Issue #296
  data.json
  src/app/(pages)/AddSpotlight/page.jsx
  src/app/(pages)/careers/page.jsx
  src/components/Global/AddSpotlightForm.jsx
Labels: gssoc-ext, level3

#353 Added Support in Stories and Achievements Page, of JSON Server along with the Add stories and Achievement Feature | Issue #297
  PROJECT_STRUCTURE.md
  data.json
  repo_structure.txt
  src/app/(pages)/AddStories/page.jsx
  src/app/(pages)/Stories-Achievements/page.jsx
  src/components/Global/AddStoriesForm.jsx
Labels: gssoc-ext, level3

#327 /careers end point and fetching from the end point
  data.json
  src/app/(pages)/careers/page.jsx
Labels: gssoc-ext, level2

#331 Updated README.md
  README.md
Labels: gssoc-ext, level1

#365 #340 Added Frontend Developer Roadmap
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3, hacktoberfest, hacktoberfest-accepted

#367 Add SDK Framework Page for enhanced developer tools and integration resources.
  public/sdk1.png
  public/sdk2.png
  public/sdk3.png
  public/sdk4.png
  src/app/(pages)/sdk/page.jsx
  src/components/Global/ProductsNavbar.jsx
Labels: gssoc-ext, level3

#371 Add DevOps and CI/CD Tools to Developer Products Section
  public/cicd1.png
  public/cicd2.jpg
  public/cicd3.jpg
  public/cicd4.jpg
  public/cicd5.jpg
  src/app/(pages)/cicd/page.jsx
Labels: gssoc-ext, level2

#368 add operation system
  public/os1.png
  public/os2.ico
  public/os3.svg
  public/os4.png
  src/app/(pages)/operating-system/page.jsx
Labels: gssoc-ext, level3

#372 ADD Developers & Practitioners Page to the application
  src/app/(pages)/Practitioners/page.jsx
Labels: gssoc-ext, level2

#374 #366 Added the Backend Development Roadmap
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/[id]/page.jsx
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#376 Create security.md
  security.md
Labels: gssoc-ext, level1

#377 Add "Back to Top" in readme
  README.md
Labels: gssoc-ext, level1

#378 fix contact us button
  src/components/Global/Hero.jsx
Labels: gssoc-ext, level1

#381 Changes
  data.json
  src/app/(pages)/AddHackathon/page.jsx
  src/app/(pages)/Stories-Achievements/mentors.js
  src/app/(pages)/Stories-Achievements/page.jsx
  src/app/(pages)/api/subscribe/route.js
  src/app/(pages)/careers/page.jsx
  src/app/api/Certifications/data.js
  src/app/api/Certifications/route.js
  src/app/api/addhackathon/route.js
  src/app/api/addstoriesapi/route.js
  src/app/api/chapters/data.js
  src/app/api/chapters/route.js
  src/app/api/generate-content/route.js
  src/app/api/subscribe/route.js
  src/components/Global/AddHackathonForm.jsx
  src/components/Global/AddStoriesForm.jsx
Labels: gssoc-ext, level2

#382 #375 Implemented UI/UX Development Roadmap
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#386 #383 Added Cloud Computing and DevOps Roadmap
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3, hacktoberfest

#387 Story details added
  src/app/(pages)/Stories-Achievements/[id]/page.jsx
  src/app/(pages)/Stories-Achievements/page.jsx
Labels: gssoc-ext, level3

#390 ADD Page for Transform with google cloude integration
  src/app/(pages)/transform/page.jsx
Labels: gssoc-ext, level3

#398 Enhanced Footer with Social Links
  README.md
Labels: level1

#391 ADD Partners Discover partners that can help you innovate faster with Google Cloud products and services
  src/app/(pages)/partners/page.jsx
Labels: gssoc-ext, level2

#403 Added all fields in the Add career spotlight job according to json
  src/app/(pages)/AddSpotlight/page.jsx
  src/components/Global/AddSpotlightForm.jsx
Labels: gssoc-ext, level3

#404 Made a help with future questionaire Page
  src/app/(pages)/HelpWithFuture/page.jsx
  src/app/api/generate-content/route.js
  src/components/Global/HelpWithFutureForm.jsx
Labels: gssoc-ext, level3

#405 ADD play The Arcade with Google Cloud
  public/arcade1.png
  public/arcade2.png
  src/app/(pages)/arcade/page.jsx
Labels: level3

#406 ADD The top AI courses for a summer of learning with Google Cloud
  public/summer_learning_hero.png
  src/app/(pages)/google-cloud-learning/page.jsx
Labels: gssoc-ext, level3

#407 ADD Build what's next in generative AI
  public/genai1.jpg
  public/genai2.webp
  src/app/(pages)/genai/page.jsx
Labels: gssoc-ext, level3

#421 Update About Page
  src/app/(pages)/About/page.jsx
Labels: gssoc-ext, level2

#412 open source resources are added : #402 done
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level2

#415 ADD Grounding generative AI in enterprise truth(GENAI)
  public/truth1.png
  src/app/(pages)/truth/page.jsx
Labels: gssoc-ext, level3

#416 ADD Weeklies | Build your Optimal Gen AI Roadmap for ROI
  public/week1.png
  src/app/(pages)/weekly/page.jsx
Labels: gssoc-ext, level3

#417 ADD Ai-Ml and Appllication development page
  src/app/(pages)/ai-ml/page.jsx
  src/app/(pages)/application-dev/page.jsx
Labels: gssoc-ext, level3

#418 Add 2PAGES compute tech and hositng page to the application
  src/app/(pages)/compute-tech/page.jsx
  src/app/(pages)/hosting/page.jsx
Labels: gssoc-ext, level3

#419 Add 2Pages db overview and analytics page
  src/app/(pages)/analytics-pipelines/page.jsx
  src/app/(pages)/db-overview/page.jsx
Labels: gssoc-ext, level3

#428 Add Distributed, hybrid, and multicloud overview
  src/app/(pages)/distributed-hybrid/page.jsx
Labels: level2

#429 Add Generative AI Overview page to the application
  src/app/(pages)/generative-ai-overview/page.jsx
Labels: gssoc-ext, level3

#430 Add Industry Solutions Overview page to the application
  src/app/(pages)/industry-solutions/page.jsx
Labels: gssoc-ext, level3

#432 Add Observability and monitoring overview
  src/app/(pages)/observability-view/page.jsx
Labels: gssoc-ext, level3

#433 Add security and overview implemenation for the applicationn
  src/app/(pages)/security-overview/page.jsx
Labels: gssoc-ext, level2

#434 Add storage and overview to the implementation
  src/app/(pages)/storage-overview/page.jsx
Labels: gssoc-ext, level3

#436 Backend Issue Report Template
  .github/ISSUE_TEMPLATE/backend_issue.yml
Labels: gssoc-ext, level1

#437 Front end Issue Report Template
  .github/ISSUE_TEMPLATE/frontend_issue.yml
Labels: gssoc-ext, level1

#441 Add join partner page for connecting people to the comunity
  src/app/(pages)/join-partner/page.jsx
Labels: gssoc-ext, level3

#444 Add analyst report page to the application for thorough review fo reports data
  src/app/(pages)/analyst-reports/page.jsx
Labels: gssoc-ext, level3

#445 Implemented the Blogs Page | Search and SortBy Lexicographically Order(Increasing and Decreasing) | Fully Responsive | Issue #427
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Blogs/Blogs.js
  src/app/(pages)/Blogs/page.jsx
Labels: gssoc-ext, level3

#447 Implemented the Extended Blogs Page | Fully Responsive | Issue #427
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Blogs/Blogs.js
  src/app/(pages)/Blogs/[id]/page.jsx
  src/app/(pages)/Blogs/page.jsx
Labels: level3, hacktoberfest

#451 #423 Added Machine Learning & AI Roadmap
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#453 #452 Added the Blockchain Development Roadmap
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#470 Stories and Achievements section
  src/app/(pages)/Stories-Achievements/page.jsx
  src/components/ui/achievements.jsx
  src/components/ui/stories.jsx
Labels: gssoc-ext, level3

#462 Add featured whitepapers page
  src/app/(pages)/whitepapers/page.jsx
Labels: gssoc-ext, level3

#463 ADD Service and health page fro the google developers resources
  src/app/(pages)/service-health/page.jsx
Labels: gssoc-ext, level3

#464 Add press corner page
  public/press1.jpg
  src/app/(pages)/press-corner/page.jsx
Labels: gssoc-ext, level3

#465 ADD gen-studio page to the Gemini page collection to the application
  public/gen-studio.png
  public/gen-studio2.svg
  src/app/(pages)/gen-studio/page.jsx
Labels: gssoc-ext, level3

#466 Add code-exchange page for better collaboration and easy connectivity
  src/app/(pages)/code-exchange/page.jsx
Labels: gssoc-ext, level3

#467 Add api story line page to the application
  src/app/(pages)/storytime/page.jsx
Labels: gssoc-ext, level3

#468 Add moonshots page to the application
  src/app/(pages)/moonshots/page.jsx
Labels: gssoc-ext, level3

#469 Add the sandbox page to the application
  src/app/(pages)/sandbox/page.jsx
Labels: gssoc-ext, level3

#474 Game Dev Roadmap
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#475 Loginadded on signup page.
  src/app/(pages)/SignUp/page.jsx
Labels: gssoc-ext, level1

#484 Fix responsiveness for the application
  src/app/layout.js
  src/components/Global/Sidebar.jsx
Labels: gssoc-ext, level1

#485 Add easter egg page to the application
  src/app/(pages)/easter-egg/page.jsx
Labels: gssoc-ext, level3

#486 Add garage page for the application
  src/app/(pages)/garage/page.jsx
Labels: gssoc-ext, level3

#487 Add doodle dev zone page to the application
  public/doodl3.png
  public/doodle1.png
  public/doodle2.jpeg
  src/app/(pages)/doodle/page.jsx
Labels: gssoc-ext, level3

#488 ADD Google lens page for educating students about the google lens thing
  src/app/(pages)/lens-page/page.jsx
Labels: gssoc-ext, level3

#489 Roadmap for Robotics
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#490 ADDED LINKS IN FOOTER AS PER YOUR REQUIREMENTS..
  src/components/Global/Footer.jsx
Labels: gssoc-ext, level1, hacktoberfest

#492 ADDED GIT & GITHUB LEARNING TRACK
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#491 AR/VR Roadmap
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#495 Roadmap for Linux
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#512 Add GDG Innovation Hub Page #511
  src/app/(pages)/inovation-hub/page.jsx
Labels: gssoc-ext, level3

#513 MAKE CARDS CLICKABLES
  src/components/Global/Hero.jsx
Labels: gssoc-ext, level2

#514 Added JSON Server Support in the Blogs and Extended Blogs Page | Issue #493
  PROJECT_STRUCTURE.md
  data.json
  repo_structure.txt
  src/app/(pages)/Blogs/Blogs.js
  src/app/(pages)/Blogs/[id]/page.jsx
  src/app/(pages)/Blogs/page.jsx
  src/app/(pages)/GeminiAI/page.jsx
Labels: gssoc-ext, level3

#517 Added JSON Server Support in the Certifications Page | Issue #493
  data.json
  src/app/api/Certifications/route.js
Labels: gssoc-ext, level2

#520 added animation to the conatct page
  package-lock.json
  package.json
  src/app/(pages)/Contact/conatct.json
  src/app/(pages)/Contact/contact.css
  src/app/(pages)/Contact/page.jsx
Labels: gssoc-ext, level2

#518 Added JSON Server Support in the GDSC Chapters Page | Issue #493
  PROJECT_STRUCTURE.md
  data.json
  repo_structure.txt
  src/app/api/chapters/route.js
Labels: gssoc-ext, level2

#526 added rest pass page and email functionallity
  package-lock.json
  package.json
  src/app/(pages)/ResetPassword/page.jsx
  src/app/api/SendResetPassword/image.png
  src/app/api/SendResetPassword/route.js
Labels: gssoc-ext, level3

#519 Added JSON Server Support in the FAQs and Forums Page | Issue #493
  data.json
  src/app/(pages)/FAQsForum/page.jsx
Labels: gssoc-ext, level2

#538 Add gdg history page to the application
  src/app/(pages)/volunteer/page.jsx
Labels: gssoc-ext, level3

#537 Added JSON Server Support in the Growth Page | Issue #493
  PROJECT_STRUCTURE.md
  data.json
  repo_structure.txt
  src/app/(pages)/growth/page.jsx
Labels: gssoc-ext, level2

#539 Add future page
  src/app/(pages)/future-tech/page.jsx
Labels: gssoc-ext, level3

#540 Add tech confessions for the tech dev students
  src/app/(pages)/confession/page.jsx
Labels: gssoc-ext, level3

#541 Add unsolved mystery tech
  src/app/(pages)/mystery/page.jsx
Labels: gssoc-ext, level3

#542 Add retro corner page to the applciation
  src/app/(pages)/retro/page.jsx
Labels: gssoc-ext, level3

#544 Add ai art gallery to the applcication
  public/art1.jpeg
  public/art2.jpeg
  public/art3.jpeg
  public/art4.jpeg
  public/art5.jpeg
  src/app/(pages)/ai-art-gallery/page.jsx
Labels: gssoc-ext, level3

#545 ADd detox zone page
  src/app/(pages)/detox-zone/page.jsx
Labels: gssoc-ext, level3

#546 Add Developer Nightmares Page to the application
  src/app/(pages)/dev-nightmare/page.jsx
Labels: gssoc-ext, level3

#547 Added Search and Filter Features | Issue #534
  data.json
  src/app/(pages)/growth/page.jsx
Labels: gssoc-ext, level3

#548 Add reverse engineering page to the application
  src/app/(pages)/ReverseEngineeringLab/page.jsx
Labels: gssoc-ext, level3

#549 Add voyage page to the application
  public/voy1.png
  public/voy2.jpeg
  public/voy3.png
  src/app/(pages)/Voyages/page.jsx
Labels: gssoc-ext, level3

#552 Added Search and Filter Features on Growth Page | PR 1 | Issue #550
  src/app/(pages)/whitepapers/page.jsx
Labels: gssoc-ext, level3

#554 Added JSON Server Support in the Analyst Reports Page | Issue #493
  data.json
  src/app/(pages)/analyst-reports/page.jsx
Labels: gssoc-ext, level3

#558 Added JSON Server Support in the Dev Products Page | Issue #493
  data.json
  src/app/(pages)/devprod/page.jsx
Labels: gssoc-ext, level3

#556 #516 Added the SRE Roadmap
  src/app/(pages)/Resources/resources.js
Labels: gssoc-ext, level3

#559 Added Search and Filter Features on DevProd Page | PR 3 | Issue #550
  src/app/(pages)/devprod/page.jsx
Labels: gssoc-ext, level3
